# Base image with R and CentOS 7
FROM centos:7

# Install system dependencies
RUN yum update -y && \
    yum install -y epel-release && \
    yum install -y R && \
    yum install -y libcurl-devel openssl-devel git && \
    yum install -y -libxml2-devel libdigit-devel

# Set up the working directory
WORKDIR /home/mkb/usr/mytmp

# Install renv and restore the project
RUN R -e 'install.packages("renv")'
RUN R -e 'renv::restore()'

# Expose the default Shiny port
EXPOSE 3838

# Set the command to run the app
CMD ["R", "-e", "shiny::runApp(host='0.0.0.0', port=3838)"]
